apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kuard
spec:
  rules:
  - host: {{ .Values.hostname }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kuard-helm
            port:
              number: 80